purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.688172
  lightness: 0.5913978
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#6690C0'
    - '#383430'
    - '#7F6C51'
  rhythmicContrast: 0.3584229
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Glasslion
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1146953
layout_spectrum: 1
