name: Glasslion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5C88A3'
    - '#CFD7E9'
    - '#385465'
    - '#027778'
  brandStrength: 0.0625
  lightness: 0.3189082
  saturation: 1
  rhythmicContrast: 0.3584229
purpose: []
